name: Test
on: [push, pull_request]
jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Setup
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Checkout
      uses: actions/checkout@v1

    - name: Test
      run: go test -v -race -covermode atomic -coverprofile coverage.out

    - name: Coverage
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{secrets.codecov}}
